---
- name: Configure Linux image with Docker and Kubernetes and nginx
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
      - name: Update all packages to current version
        apt:
            update_cache: yes
            upgrade: dist

      - name: Install Kubernetes Snap
        shell: snap install microk8s --edge --classic

      - name: Alias kubectl
        shell: snap alias microk8s.kubectl kubectl

      - name: Install Docker
        apt:
            name: docker.io
            state: present
            update_cache: yes

      - name: enable Docker service and ensure not masked
        systemd:
            name: docker
            enabled: yes
            masked: no

      - name: Start Docker
        systemd:
            state: started
            name: docker

      - name: Add Docker Group
        group:
            name: docker
            state: present

      - name: Add user to Docker Group
        user:
            name: vagrant
            groups: docker
            append: yes

      - name: Copy vimrc to VM
        copy:
            src: cfg/vimrc
            dest: /home/vagrant/.vimrc
            force: no

      - name: Clear APT cache
        apt:
            autoclean: yes

      - name: Remove unwanted dependencies
        apt:
            autoremove: yes

            #- name: Reboot system
            #reboot:
...
